(* ::Package:: *)

(* ::Input::Initialization:: *)
(**)
(*\!\(TraditionalForm\`\(\**)
(*OverscriptBox[*)
(*StyleBox["W", "TI"], "~"] \((\**)
(*OverscriptBox[*)
(*StyleBox["R", "TI"], "^"])\)\(==\)\(\n\)*)
(*\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(+\[Infinity]\)]\**)
(*FractionBox[*)
(*RowBox[{*)
(*StyleBox["d", "TI"], *)
(*StyleBox["x", "TI"], "exp", *)
(*RowBox[{"\[ScriptDotlessI]", *)
(*StyleBox["x", "TI"]}]}], *)
(*RowBox[{"2", "\[Pi]"}]] *)
(*\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(+\[Infinity]\)]\**)
(*FractionBox[*)
(*StyleBox[*)
(*RowBox[{"d", "y"}], "TI"], *)
(*RowBox[{"2", "\[Pi]\[ScriptDotlessI]", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*StyleBox["y", "TI"], "-", "\[ScriptDotlessI]\[Epsilon]"}], ")"}]}]] \**)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], "(", *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]], "-", *)
(*StyleBox["y", "TI"], "\[GothicCapitalI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], ")"}], *)
(*RowBox[{*)
(*RowBox[{"-", "1"}], "/", "2"}]]\(==\)\(\n\)*)
(*\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(+\[Infinity]\)]\**)
(*FractionBox[*)
(*RowBox[{*)
(*StyleBox["d", "TI"], *)
(*StyleBox["x", "TI"], "exp", *)
(*RowBox[{"\[ScriptDotlessI]", *)
(*StyleBox["x", "TI"]}]}], *)
(*RowBox[{"2", "\[Pi]"}]] \**)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], "(", *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], ")"}], *)
(*RowBox[{*)
(*RowBox[{"-", "1"}], "/", "2"}]] *)
(*StyleBox["H", "TI"] \((\**)
(*FractionBox[*)
(*RowBox[{"\[GothicCapitalI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}]])\)\(;\)\(\n\)\)\)*)
(**)
(*\!\(TraditionalForm\`\**)
(*StyleBox["H", "TI"] \((\**)
(*StyleBox["I", "TI"])\) == *)
(*\*FractionBox[\(1\), \(2\)] + *)
(*\*FractionBox[\(1\), \(\[Pi]\)] *)
(*\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(+\[Infinity]\)]\**)
(*StyleBox["d", "TI"] \**)
(*StyleBox["y", "TI"] \**)
(*FractionBox[*)
(*SubscriptBox[*)
(*RowBox[{"[", *)
(*RowBox[{*)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], *)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", "+", *)
(*StyleBox["y", "TI"], *)
(*SubscriptBox[*)
(*StyleBox["I", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], *)
(*RowBox[{*)
(*RowBox[{"-", "1"}], "/", "2"}]]}], "]"}], "-"], *)
(*StyleBox["y", "TI"]]\)*)
(**)
(**)


(* ::Input::Initialization:: *)
ClearAll[H,W];


(* ::Input::Initialization:: *)
H[RR_, x_ ]/;VectorQ[RR,NumericQ]:=
Block[{S,Q, y,II,Sing, tol = 10^(-25)},
II = Im[RR]/(x -  RR);
S =1/ Sqrt[Times @@(1 + y  II)];
Q = (S -(S/.y->-y))y/(tol+ y^2);
Sing[z_]:=  z- #  + Im[#]==0 &/@RR;
(*Print["Sing[z]=", Sing[z]];*)
1/2 +1/(2Pi) NIntegrate[ Q,{y,0,Infinity},Exclusions->Sing[y],
PrecisionGoal->12,WorkingPrecision->16, Method->"GaussKronrodRule", MaxRecursion->30]
]//Quiet;


(* ::Input:: *)
(*RR1 = {Random[Complex],Random[Complex],Random[Complex]}*)


(* ::Input:: *)
(*H[RR1,1.]*)


(* ::Input:: *)
(*\!\(TraditionalForm\`*)
(*\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(+\[Infinity]\)]\**)
(*FractionBox[*)
(*RowBox[{*)
(*StyleBox["d", "TI"], *)
(*StyleBox["x", "TI"], "exp", *)
(*RowBox[{"\[ScriptDotlessI]", *)
(*StyleBox["x", "TI"]}]}], *)
(*RowBox[{"2", "\[Pi]"}]] \**)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], "(", *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], ")"}], *)
(*RowBox[{*)
(*RowBox[{"-", "1"}], "/", "2"}]] \**)
(*StyleBox["H", "TI"] \((\**)
(*FractionBox[*)
(*RowBox[{"\[GothicCapitalI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}]])\);\)*)


(* ::Input::Initialization:: *)
W[RR_]/;VectorQ[RR,NumericQ]:=
Block[{Sing, x},
Sing[z_] := (z== #) &/@RR;
(*Print["Sing[z]=", Sing[z]];*)
NIntegrate[Exp[I x]/(2 Pi) /Sqrt[Times@@(x -RR)]Evaluate[ H[RR,x]],{x,-Infinity,Infinity},
Exclusions->Sing[x],
PrecisionGoal->12,WorkingPrecision->16, Method->"DoubleExponentialOscillatory", MaxRecursion->30]
]//Quiet;


(* ::Input:: *)
(**)
(**)
(*W[ RR1]*)
