(* ::Package:: *)

(* ::Input:: *)
(**)
(*\!\(TraditionalForm\`\**)
(*StyleBox["P", "TI"] \((\**)
(*StyleBox["x", "TI"])\) + \**)
(*StyleBox["Q", "TI"] \((\**)
(*StyleBox["x", "TI"])\) == \**)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True]\**)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", "+", "\[ScriptDotlessI]", *)
(*StyleBox["x", "TI"], "\[GothicCapitalI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], *)
(*RowBox[{"-", *)
(*FractionBox["1", "2"], "-", *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]]}]]\)*)
(*\!\(TraditionalForm\`\**)
(*StyleBox["H", "TI"] \((\[GothicCapitalI] \**)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]], \**)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]])\) == *)
(*\*FractionBox[\(1\), \(2\)] + *)
(*\*FractionBox[\(1\), \(\[Pi]\)] *)
(*\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(+\[Infinity]\)]\**)
(*StyleBox["d", "TI"] \**)
(*StyleBox["x", "TI"] \**)
(*FractionBox[*)
(*RowBox[{*)
(*StyleBox["Q", "TI"], "(", *)
(*StyleBox["x", "TI"], ")"}], *)
(*StyleBox["x", "TI"]]\)*)


(* ::Input:: *)
(*ClearAll[QQ,H,BB];*)


(* ::Input:: *)
(*QQ[xx_, nn_ ]/;VectorQ[xx,NumericQ]&& VectorQ[nn,NumericQ]:= *)
(*(*Im prod( 1 + I x )^n*)*)
(*Product[(1 + xx[[k]]^2)^(nn[[k]]/2),{k,Length[nn]}] Sin[ Sum[nn[[k]]ArcTan[xx[[k]]]  ,{k,Length[nn]}]]*)


(* ::Input:: *)
(*H[II_ ,nn_]/;VectorQ[II,NumericQ]&& VectorQ[nn,NumericQ]:=*)
(*Block[{Q, x, tol = 10^(-25)},*)
(*Q[x_] :=QQ[x II,-nn-1/2]x/(tol+ x^2);*)
(* (*Product[(1 + I x II[[k]])^(-1/2 -nn[[k]]),{k,Length[nn]}];*)*)
(*1/2 +1/Pi NIntegrate[ Q[x],{x,0,Infinity},Exclusions->None,*)
(*PrecisionGoal->12,WorkingPrecision->16, Method->"GaussKronrodRule", MaxRecursion->20]*)
(*];*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*H[{1.,1.+ I,4.,-1.}, {1,1,2,0}]*)


(* ::Input:: *)
(*\!\(TraditionalForm\`\**)
(*OverscriptBox[*)
(*StyleBox["W", "TI"], "~"] \((\**)
(*OverscriptBox[*)
(*StyleBox["R", "TI"], "^"])\) == \**)
(*UnderscriptBox["\[Sum]", *)
(*RowBox[{*)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], "1"], *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], "2"], *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], "3"], *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], "4"]}],*)
(*LimitsPositioning->True]\**)
(*FractionBox[*)
(*RowBox[{*)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], *)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{"-", "\[ScriptDotlessI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]]], *)
(*TemplateBox[{RowBox[{"-", FractionBox["1", "2"]}], SubscriptBox[StyleBox["n", "TI"], StyleBox["k", "TI"]]},*)
(*"Binomial"]}], *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{"1", "+", *)
(*UnderoverscriptBox["\[Sum]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True], *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], "!"}]] \**)
(*StyleBox["H", "TI"] \((\[GothicCapitalI] \**)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]], \**)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]])\); \n\**)
(*StyleBox["H", "TI"] \((\[GothicCapitalI] \**)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]], \**)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]])\) == *)
(*\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(+\[Infinity]\)]\**)
(*FractionBox[*)
(*StyleBox[*)
(*RowBox[{"d", "x"}], "TI"], *)
(*RowBox[{"2", "\[Pi]\[ScriptDotlessI]", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*StyleBox["x", "TI"], "-", "\[ScriptDotlessI]\[Epsilon]"}], ")"}]}]] \**)
(*UnderoverscriptBox["\[Product]", *)
(*RowBox[{*)
(*StyleBox["k", "TI"], "==", "1"}], "4",*)
(*LimitsPositioning->True]\**)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{"1", "+", "\[ScriptDotlessI]", *)
(*StyleBox["x", "TI"], "\[GothicCapitalI]", *)
(*SubscriptBox[*)
(*StyleBox["R", "TI"], *)
(*StyleBox["k", "TI"]]}], ")"}], *)
(*RowBox[{"-", *)
(*FractionBox["1", "2"], "-", *)
(*SubscriptBox[*)
(*StyleBox["n", "TI"], *)
(*StyleBox["k", "TI"]]}]]\)*)


(* ::Input:: *)
(*BB[RR_, M_]/;VectorQ[RR,NumericQ]:=*)
(*Block[{II = Im[RR],n1,n2,n3, n4},*)
(*ParallelSum[*)
(*Block[{m1,m2,m3},*)
(*n1 = m1;*)
(*n2 = m2-m1;*)
(*n3 = m3 - m2;*)
(*n4 = M - m3;*)
(*Binomial[-1/2,n1](-I RR[[1]])^n1 *)
(*Binomial[-1/2,n2](-I RR[[2]])^n2 *)
(*Binomial[-1/2,n3](-I RR[[3]])^n3*)
(*Binomial[-1/2,n4](-I RR[[4]])^n4*)
(*H[II,{n1,n2,n3,n4}]*)
(*],{m3,0,M},{m2,0,m3},{m1,0,m2}*)
(*]*)
(*];*)


(* ::Input:: *)
(*BB[{1. + I, 2. + 2 I, -1. - I, -2. - I}, 16]*)


(* ::Input:: *)
(*RR1= {1. + I, 2. + 2 I, -1. - I, -2. - I};*)


(* ::Input:: *)
(*ClearAll[WResult,T,G,P,x];*)


(* ::Input:: *)
(*GetCoeffs[RR_, M_]:=Table[BB[RR,k]/(k+1)!,{k,0,M}];*)


(* ::Input:: *)
(**)
(*coeffs = GetCoeffs[RR1, 20];*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*Wtest[ coeffs_, x0_]:=*)
(*Block[{G, T,P, x, ans1, ans2,ans3, M = Length[coeffs]-1},*)
(*Print["straight sum =",Sum[coeffs[[k]] x0^(k-1),{k,M+1}]];*)
(*G = Sum[ coeffs[[k]]/coeffs[[1]] x^(k-1),{k,M+1}];*)
(*T = Normal[Log[G + O[x]^(M+1)]]//Simplify;*)
(*Print["log expansion =",T];*)
(*ans1 = N[coeffs[[1]] Exp[T]/.x->x0,10];*)
(*Print["exp log expansion =",ans1];*)
(*P = PadeApproximant[T,{x,0,{M/2,M/2-1}}];*)
(*ans2 = N[coeffs[[1]] Exp[P]/.x->x0,10];*)
(*Print["exp Pade ",M/2,",",M/2-1," =",ans2];*)
(*P = PadeApproximant[T,{x,0,{M/2,M/2}}];*)
(*ans3 = N[coeffs[[1]] Exp[P]/.x->x0,10];*)
(*Print["exp Pade ",M/2,",",M/2," =",ans3];*)
(*P = PadeApproximant[T,{x,0,{M/2-1,M/2}}];*)
(*ans4 = N[coeffs[[1]] Exp[P]/.x->x0,10];*)
(*Print["exp Pade ",M/2-1,",",M/2," =",ans4];*)
(*]*)


(* ::Input:: *)
(*WResult[coeffs,4.]*)


(* ::Input:: *)
(*Wbest[RR_]:=*)
(*Block[{coeffs,G, T,P, x, ans1, ans2,ans3, M=16, x0=1.},*)
(*coeffs =  GetCoeffs[RR, 16];*)
(*G = Sum[ coeffs[[k]]/coeffs[[1]] x^(k-1),{k,M+1}];*)
(*T = Normal[Log[G + O[x]^(M+1)]]//Simplify;*)
(*P = PadeApproximant[T,{x,0,{M/2,M/2-1}}];*)
(*N[coeffs[[1]] Exp[P]/.x->x0,10]*)
(*];*)


(* ::Input:: *)
(*Wbest[RR1]*)
